import type { MappingProject } from './schema';

export const exportGeoJSON = (project: MappingProject): string => JSON.stringify({ type: 'FeatureCollection', features: project.features.map((feature) => ({ type: 'Feature', id: feature.id, geometry: feature.geometry, properties: { ...feature.properties, layerId: feature.layerId } })) }, null, 2);
export const exportCSV = (project: MappingProject): string => { const rows = [['id', 'layerId', 'geometry', 'coordinates', ...project.schema.map((field) => field.name)]]; for (const feature of project.features) rows.push([feature.id, feature.layerId, feature.geometry.type, JSON.stringify(feature.geometry.coordinates), ...project.schema.map((field) => String(feature.properties[field.name] ?? ''))]); return rows.map((row) => row.map((value) => `"${value.replaceAll('"', '""')}"`).join(',')).join('\n'); };
export const exportKML = (project: MappingProject): string => `<kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${project.name}</name>${project.features.map((feature) => `<Placemark><name>${feature.id}</name><ExtendedData><Data name="layerId"><value>${feature.layerId}</value></Data></ExtendedData>${feature.geometry.type === 'Point' ? `<Point><coordinates>${feature.geometry.coordinates.join(',')},0</coordinates></Point>` : feature.geometry.type === 'LineString' ? `<LineString><coordinates>${feature.geometry.coordinates.map((point) => `${point[0]},${point[1]},0`).join(' ')}</coordinates></LineString>` : `<Polygon><outerBoundaryIs><LinearRing><coordinates>${(feature.geometry.coordinates[0] ?? []).map((point) => `${point[0]},${point[1]},0`).join(' ')}</coordinates></LinearRing></outerBoundaryIs></Polygon>`}</Placemark>`).join('')}</Document></kml>`;
export const exportBackup = (project: MappingProject): string => JSON.stringify({ format: 'community-mapping-backup', version: 1, project }, null, 2);
export const isBackup = (value: unknown): value is { project: MappingProject } => Boolean(value && typeof value === 'object' && (value as { format?: string }).format === 'community-mapping-backup');
export const download = (filename: string, body: string, type = 'application/octet-stream'): void => { const url = URL.createObjectURL(new Blob([body], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 0); };

export interface EncryptedBackupEnvelope { format: 'community-mapping-encrypted-backup'; version: 1; salt: string; iv: string; ciphertext: string; }
const b64 = (data: Uint8Array): string => btoa(String.fromCharCode(...data));
export const encryptBackup = async (project: MappingProject, password: string): Promise<string> => { if (password.length < 8) throw new Error('Password must contain at least 8 characters'); if (!crypto.subtle) throw new Error('Web Crypto is unavailable'); const encoder = new TextEncoder(); const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const material = await crypto.subtle.importKey('raw', encoder.encode(password), 'PBKDF2', false, ['deriveKey']); const key = await crypto.subtle.deriveKey({ name: 'PBKDF2', salt: salt as unknown as BufferSource, iterations: 210000, hash: 'SHA-256' }, material, { name: 'AES-GCM', length: 256 }, false, ['encrypt']); const ciphertext = await crypto.subtle.encrypt({ name: 'AES-GCM', iv: iv as unknown as BufferSource }, key, encoder.encode(exportBackup(project))); return JSON.stringify({ format: 'community-mapping-encrypted-backup', version: 1, salt: b64(salt), iv: b64(iv), ciphertext: b64(new Uint8Array(ciphertext)) } satisfies EncryptedBackupEnvelope, null, 2); };
