import type { ToolModule } from '../../core/tool-contract';
import { downloadUrl, getErrorMessage, setToolStatus } from '../../core/tool-ui';
import { metadata } from './metadata';

interface ContactImage { file: File; image: HTMLImageElement; }
let panel: HTMLElement | undefined; let images: ContactImage[] = []; let outputUrl = '';

function drawSheet(canvas: HTMLCanvasElement, items: ContactImage[], columns: number, showLabels: boolean): void {
  const cellWidth = 240; const cellHeight = showLabels ? 205 : 180; const rows = Math.max(1, Math.ceil(items.length / columns)); const padding = 24; canvas.width = padding + columns * (cellWidth + padding); canvas.height = padding + rows * (cellHeight + padding); const context = canvas.getContext('2d'); if (!context) return; context.fillStyle = '#f8fafc'; context.fillRect(0, 0, canvas.width, canvas.height); context.font = '14px system-ui'; context.textAlign = 'center';
  items.forEach((item, index) => { const x = padding + (index % columns) * (cellWidth + padding); const y = padding + Math.floor(index / columns) * (cellHeight + padding); context.fillStyle = '#ffffff'; context.fillRect(x, y, cellWidth, cellHeight); const ratio = Math.min((cellWidth - 24) / item.image.naturalWidth, (cellHeight - (showLabels ? 48 : 24)) / item.image.naturalHeight); const width = item.image.naturalWidth * ratio; const height = item.image.naturalHeight * ratio; context.drawImage(item.image, x + (cellWidth - width) / 2, y + 12 + (cellHeight - (showLabels ? 48 : 24) - height) / 2, width, height); if (showLabels) { context.fillStyle = '#172033'; context.fillText(item.file.name.slice(0, 30), x + cellWidth / 2, y + cellHeight - 18); } });
}

const tool: ToolModule = {
  metadata,
  mount(container) {
    panel = document.createElement('section'); panel.className = 'utility-panel';
    panel.innerHTML = `<div class="utility-panel__header"><div><p class="eyebrow">Image catalog</p><h2>จัดแคตตาล็อกรูปภาพ / Contact sheet</h2><p class="helper-text">รวมภาพหลายไฟล์เป็นแผ่น catalog พร้อมชื่อไฟล์ โดยรูปภาพไม่ออกจากอุปกรณ์</p></div></div><label class="file-drop" for="contact-files"><strong>เลือกรูปภาพหลายไฟล์ / Select images</strong><span>PNG, JPEG, WebP · แนะนำไม่เกิน 100 รูปต่อครั้ง</span><input id="contact-files" type="file" accept="image/png,image/jpeg,image/webp" multiple /></label><div class="form-row"><label class="field" for="contact-columns"><span>Columns</span><input id="contact-columns" type="number" min="1" max="6" value="3" /></label><label class="field field--check" for="contact-labels"><span>แสดงชื่อไฟล์ / Show labels</span><input id="contact-labels" type="checkbox" checked /></label></div><div class="contact-preview" id="contact-preview" hidden><canvas id="contact-canvas" aria-label="Contact sheet preview"></canvas></div><div class="tool-actions"><button class="button button--primary" type="button" data-contact-action="render">สร้าง Preview / Build preview</button><button class="button" type="button" data-contact-action="download" hidden>ดาวน์โหลด PNG / Download</button><button class="text-button" type="button" data-contact-action="clear">ล้างข้อมูล / Clear</button></div><output id="contact-status" class="tool-status" aria-live="polite">เลือกภาพเพื่อเริ่มต้น</output>`;
    panel.querySelector<HTMLInputElement>('#contact-files')?.addEventListener('change', async (event) => { const files = [...((event.currentTarget as HTMLInputElement).files ?? [])]; images = []; try { images = await Promise.all(files.slice(0, 100).map(async (file) => { const image = new Image(); image.src = URL.createObjectURL(file); await image.decode(); return { file, image }; })); setToolStatus(panel!.querySelector<HTMLOutputElement>('#contact-status')!, `${images.length} images loaded / โหลดรูปภาพสำเร็จ`, 'success'); } catch (error) { setToolStatus(panel!.querySelector<HTMLOutputElement>('#contact-status')!, getErrorMessage(error), 'error'); } });
    panel.addEventListener('click', (event) => { const action = (event.target as HTMLElement).closest<HTMLElement>('[data-contact-action]')?.dataset.contactAction; if (!action) return; const status = panel!.querySelector<HTMLOutputElement>('#contact-status')!; try { if (action === 'render') { if (!images.length) throw new Error('กรุณาเลือกรูปภาพอย่างน้อยหนึ่งไฟล์'); const canvas = panel!.querySelector<HTMLCanvasElement>('#contact-canvas')!; drawSheet(canvas, images, Math.max(1, Math.min(6, Number((panel!.querySelector('#contact-columns') as HTMLInputElement).value) || 3)), (panel!.querySelector('#contact-labels') as HTMLInputElement).checked); panel!.querySelector<HTMLElement>('#contact-preview')?.removeAttribute('hidden'); canvas.toBlob((blob) => { if (!blob) return; if (outputUrl) URL.revokeObjectURL(outputUrl); outputUrl = URL.createObjectURL(blob); panel!.querySelector<HTMLButtonElement>('[data-contact-action="download"]')?.removeAttribute('hidden'); }, 'image/png'); setToolStatus(status, 'สร้าง contact sheet สำเร็จ / Preview ready', 'success'); } if (action === 'download' && outputUrl) downloadUrl(outputUrl, 'image-contact-sheet.png'); if (action === 'clear') { images = []; panel!.querySelector<HTMLElement>('#contact-preview')?.setAttribute('hidden', ''); } } catch (error) { setToolStatus(status, getErrorMessage(error), 'error'); } });
    container.append(panel);
  },
  unmount() { if (outputUrl) URL.revokeObjectURL(outputUrl); images.forEach(({ image }) => { if (image.src.startsWith('blob:')) URL.revokeObjectURL(image.src); }); panel?.remove(); panel = undefined; images = []; outputUrl = ''; },
};

export const { mount, unmount } = tool;
export { metadata };
