import type { ToolModule } from '../../core/tool-contract';
import { metadata } from './metadata';

let cleanup: (() => void) | undefined;
const english = (): boolean => window.localStorage.getItem('utility-hub:locale') === 'en';
const copy = () => english() ? { start: 'Start game', restart: 'Play again', resetBest: 'Reset best', level: 'Level', score: 'Score', best: 'Best', watch: 'Watch the pattern', repeat: 'Your turn', correct: 'Correct!', wrong: 'Game over — start again', intro: 'Watch the glowing sequence, then repeat it.', ready: 'Ready for a memory challenge' } : { start: 'เริ่มเกม', restart: 'เล่นอีกครั้ง', resetBest: 'ล้างสถิติสูงสุด', level: 'รอบ', score: 'คะแนน', best: 'สถิติสูงสุด', watch: 'จำลำดับสี', repeat: 'ตาของคุณ', correct: 'ถูกต้อง!', wrong: 'จบเกม — กดเริ่มใหม่อีกครั้ง', intro: 'ดูไฟที่สว่างตามลำดับ แล้วกดตามให้ถูก', ready: 'พร้อมท้าทายความจำ' };

export const mount = (container: HTMLElement): void => {
  cleanup?.(); const c=copy(); const section=document.createElement('section'); section.className='game-panel game-panel--pattern'; section.innerHTML=`<div class="game-panel__header"><div><span class="eyebrow">${c.ready}</span><h2>Pattern Pulse</h2><p>${c.intro}</p></div><div class="game-panel__actions"><button class="button button--primary" data-game-start type="button">${c.start}</button><button class="button" data-game-reset-best type="button">${c.resetBest}</button></div></div><div class="game-hud" aria-live="polite"><span>${c.level}: <strong data-level>0</strong></span><span>${c.score}: <strong data-score>0</strong></span><span>${c.best}: <strong data-best>0</strong></span></div><div class="pattern-grid" data-grid role="group" aria-label="Pattern Pulse game"></div><p class="game-status" data-status>${c.ready}</p>`; container.append(section);
  const grid=section.querySelector<HTMLElement>('[data-grid]')!; const status=section.querySelector<HTMLElement>('[data-status]')!; const start=section.querySelector<HTMLButtonElement>('[data-game-start]')!; const resetBestButton=section.querySelector<HTMLButtonElement>('[data-game-reset-best]')!; const levelEl=section.querySelector<HTMLElement>('[data-level]')!; const scoreEl=section.querySelector<HTMLElement>('[data-score]')!; const bestEl=section.querySelector<HTMLElement>('[data-best]')!; const colors=['cyan','violet','coral','gold']; let sequence:number[]=[]; let input:number[]=[]; let level=0; let score=0; let accepting=false; let timers:number[]=[]; let best=Number(window.localStorage.getItem('utility-hub:pattern-pulse-best')||0); bestEl.textContent=String(best);
  const flash=(index:number)=>{const tile=grid.children[index] as HTMLElement|undefined; if(!tile)return; tile.classList.add('is-lit'); timers.push(window.setTimeout(()=>tile.classList.remove('is-lit'),360));};
  const nextRound=()=>{ accepting=false; level++; levelEl.textContent=String(level); sequence.push(Math.floor(Math.random()*4)); input=[]; status.textContent=c.watch; sequence.forEach((value,i)=>timers.push(window.setTimeout(()=>flash(value),650+i*520))); timers.push(window.setTimeout(()=>{accepting=true;status.textContent=c.repeat;},650+sequence.length*520)); };
  const finish=(success:boolean)=>{accepting=false; if(success){ score += level*10; scoreEl.textContent=String(score); status.textContent=c.correct; timers.push(window.setTimeout(nextRound,650)); } else { status.textContent=`${c.wrong} — ${c.score}: ${score}`; if(score>best){best=score;window.localStorage.setItem('utility-hub:pattern-pulse-best',String(best));bestEl.textContent=String(best);} start.textContent=c.restart; }};
  const press=(index:number)=>{if(!accepting)return; flash(index); input.push(index); const expected=sequence[input.length-1]; if(index!==expected){finish(false);return;} if(input.length===sequence.length)finish(true);};
  colors.forEach((name,index)=>{const tile=document.createElement('button');tile.type='button';tile.className=`pattern-tile pattern-tile--${name}`;tile.dataset.index=String(index);tile.setAttribute('aria-label',`${name} tile`);tile.addEventListener('click',()=>press(index));grid.append(tile);});
  const reset=()=>{timers.forEach(clearTimeout);timers=[];sequence=[];input=[];level=0;score=0;levelEl.textContent='0';scoreEl.textContent='0';start.textContent=c.restart;status.textContent=c.watch;nextRound();}; const resetBest=()=>{best=0;window.localStorage.removeItem('utility-hub:pattern-pulse-best');bestEl.textContent='0';status.textContent=c.ready;}; start.addEventListener('click',reset); resetBestButton.addEventListener('click',resetBest); cleanup=()=>{timers.forEach(clearTimeout);start.removeEventListener('click',reset);resetBestButton.removeEventListener('click',resetBest);section.remove();};
};
export { metadata }; export const unmount=()=>{cleanup?.();cleanup=undefined;}; export default { metadata, mount, unmount } satisfies ToolModule;
