import { svgAssetManifest, type SvgAssetMetadata } from '../../data/svg-assets/manifest';
import { metadata } from './metadata';
import {
  applySvgEdits, buildCssPack, buildLicensesTxt, buildManifestJson, buildSprite, createZip,
  inspectSvgMarkup, optimizeSvgMarkup, renderSvgToPng, sanitizeSvgMarkup, svgToDataUri, cssBackgroundSnippet,
  cssMaskSnippet, htmlSnippet, jsxSnippet, type ColorMode, type OptimizePreset,
} from './logic';

const FAVORITES_KEY = 'utility-hub:svg-favorites';
const RECENT_KEY = 'utility-hub:svg-recent';
const readIds = (key: string): string[] => { try { const value = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(value) ? value.filter((id): id is string => typeof id === 'string').slice(0, 40) : []; } catch { return []; } };
const saveIds = (key: string, ids: string[]) => localStorage.setItem(key, JSON.stringify([...new Set(ids)].slice(0, 40)));
const download = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 0); };
const bytes = (text: string) => new TextEncoder().encode(text);

export const mount = (container: HTMLElement): void => {
  let favorites = new Set(readIds(FAVORITES_KEY));
  let recent = readIds(RECENT_KEY);
  let selectedPack = new Set<string>();
  let current: SvgAssetMetadata = svgAssetManifest[0]!;
  let currentSvg = '';
  let inspector = inspectSvgMarkup('<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" />');
  let currentBg = 'checker';
  let currentSize = 64;
  let colorMode: ColorMode = 'preserve';
  let optimizePreset: OptimizePreset = 'safe';
  let customUploaded = false;
  let statusTimer: number | undefined;

  const setStatus = (message: string, tone: 'info' | 'success' | 'error' = 'info') => { const node = container.querySelector<HTMLElement>('#svg-status'); if (node) { node.textContent = message; node.dataset.tone = tone; } if (statusTimer) window.clearTimeout(statusTimer); statusTimer = window.setTimeout(() => { if (node) node.textContent = ''; }, 5000); };
  const assetById = (id: string) => svgAssetManifest.find((asset) => asset.id === id);
  const currentPackAssets = () => [...selectedPack].map(assetById).filter((asset): asset is SvgAssetMetadata => Boolean(asset));
  const displaySvg = () => { if (!currentSvg) return; const preview = container.querySelector<HTMLElement>('#svg-preview'); if (preview) { preview.innerHTML = currentSvg; const svg = preview.querySelector('svg'); if (svg) { svg.setAttribute('aria-label', current.title); svg.setAttribute('role', 'img'); svg.style.width = `${currentSize}px`; svg.style.height = `${currentSize}px`; } } };
  const addRecent = (id: string) => { recent = [id, ...recent.filter((item) => item !== id)].slice(0, 40); saveIds(RECENT_KEY, recent); };
  const loadAsset = async (asset: SvgAssetMetadata) => { current = asset; customUploaded = false; addRecent(asset.id); const response = await fetch(asset.assetUrl); currentSvg = sanitizeSvgMarkup(await response.text()).svg; inspector = inspectSvgMarkup(currentSvg); render(); };
  const copyText = async (value: string, label: string) => { try { await navigator.clipboard.writeText(value); setStatus(`${label} copied`, 'success'); } catch { setStatus('Clipboard is unavailable; select and copy from the preview.', 'error'); } };

  const render = () => {
    const query = (container.querySelector<HTMLInputElement>('#svg-search')?.value || '').trim().toLowerCase();
    const category = container.querySelector<HTMLSelectElement>('#svg-category')?.value || 'all';
    const style = container.querySelector<HTMLSelectElement>('#svg-style')?.value || 'all';
    const licenseFilter = container.querySelector<HTMLSelectElement>('#svg-license')?.value || 'all';
    const filtered = svgAssetManifest.filter((asset) => {
      const text = [asset.title, asset.category, ...asset.keywords].join(' ').toLowerCase();
      return (!query || text.includes(query)) && (category === 'all' || asset.category === category) && (style === 'all' || asset.style === style) && (licenseFilter === 'all' || (licenseFilter === 'free' ? !asset.attributionRequired : asset.attributionRequired));
    });
    const categories = [...new Set(svgAssetManifest.map((asset) => asset.category))];
    container.innerHTML = `<section class="utility-panel svg-asset-studio" aria-labelledby="svg-studio-title">
      <div class="svg-studio-header"><div><span class="eyebrow">LOCAL SVG WORKSPACE</span><h2 id="svg-studio-title">SVG Asset Studio</h2><p>ค้นหา → Preview → Inspect → Edit → Optimize → Export → Build Icon Pack</p></div><span class="privacy-badge">Local-only · ${svgAssetManifest.length} curated assets</span></div>
      <div class="svg-studio-toolbar"><label class="field"><span>Search SVG</span><input id="svg-search" type="search" placeholder="camera, arrow, music, business" value="${query.replace(/"/g, '&quot;')}" /></label><label class="field"><span>Category</span><select id="svg-category"><option value="all">All categories</option>${categories.map((item) => `<option value="${item}" ${item === category ? 'selected' : ''}>${item}</option>`).join('')}</select></label><label class="field"><span>Style</span><select id="svg-style"><option value="all">All styles</option>${['outline', 'filled', 'rounded', 'sharp'].map((item) => `<option value="${item}" ${item === style ? 'selected' : ''}>${item}</option>`).join('')}</select></label><label class="field"><span>License</span><select id="svg-license"><option value="all">All licenses</option><option value="free" ${licenseFilter === 'free' ? 'selected' : ''}>Attribution not required</option><option value="attribution" ${licenseFilter === 'attribution' ? 'selected' : ''}>Attribution required</option></select></label></div>
      <div class="svg-studio-layout"><aside class="svg-library" aria-label="SVG library"><div class="svg-library-heading"><strong>${filtered.length} results</strong><span>${favorites.size} favorites · ${selectedPack.size} in pack</span></div><div id="svg-grid" class="svg-asset-grid">${filtered.map((asset) => `<article class="svg-asset-card ${asset.id === current.id ? 'is-selected' : ''}" data-svg-id="${asset.id}"><button class="svg-card-open" data-action="open" data-svg-id="${asset.id}" aria-label="Open ${asset.title}"><img src="${asset.assetUrl}" alt="${asset.title} SVG preview" loading="lazy" /><strong>${asset.title}</strong><span>${asset.category} · ${asset.license}</span></button><div class="svg-card-actions"><button class="icon-button" data-action="favorite" data-svg-id="${asset.id}" aria-pressed="${favorites.has(asset.id)}" aria-label="${favorites.has(asset.id) ? 'Remove from favorites' : 'Add to favorites'} ${asset.title}">${favorites.has(asset.id) ? '★' : '☆'}</button><button class="icon-button" data-action="pack" data-svg-id="${asset.id}" aria-pressed="${selectedPack.has(asset.id)}" aria-label="${selectedPack.has(asset.id) ? 'Remove from pack' : 'Select for pack'} ${asset.title}">${selectedPack.has(asset.id) ? '✓' : '+'}</button><button class="icon-button" data-action="copy" data-svg-id="${asset.id}" aria-label="Copy ${asset.title} SVG">Copy</button></div></article>`).join('')}</div></aside>
      <main class="svg-workspace" aria-label="SVG preview and editor"><div class="svg-preview-toolbar"><label>Preview background<select id="svg-preview-bg"><option value="checker" ${currentBg === 'checker' ? 'selected' : ''}>Transparent checkerboard</option><option value="light" ${currentBg === 'light' ? 'selected' : ''}>Light</option><option value="dark" ${currentBg === 'dark' ? 'selected' : ''}>Dark</option></select></label><label>Size<select id="svg-preview-size">${[16, 24, 32, 48, 64, 128].map((size) => `<option value="${size}" ${currentSize === size ? 'selected' : ''}>${size}px</option>`).join('')}</select></label></div><div id="svg-preview" class="svg-preview svg-preview--${currentBg}" aria-label="Sanitized SVG preview"></div><div class="svg-workspace-actions"><button class="button" data-action="copy-raw">Copy SVG</button><button class="button" data-action="download-svg">Download SVG</button><button class="button button--primary" data-action="download-png">Export PNG</button></div><div id="svg-status" class="tool-status" role="status" aria-live="polite"></div><section class="svg-editor-panel"><h3>Edit and optimize</h3><div class="svg-editor-grid"><label>Color mode<select id="svg-color-mode"><option value="preserve" ${colorMode === 'preserve' ? 'selected' : ''}>Preserve original colors</option><option value="single" ${colorMode === 'single' ? 'selected' : ''}>Single color</option><option value="currentColor" ${colorMode === 'currentColor' ? 'selected' : ''}>currentColor</option></select></label><label>Color<input id="svg-color" type="color" value="#2563eb" /></label><label>Stroke width<input id="svg-stroke-width" type="number" min="0" max="20" step="0.5" value="1.5" /></label><label>Rotation<input id="svg-rotation" type="number" min="-360" max="360" value="0" /></label><label>Padding<input id="svg-padding" type="number" min="0" max="48" value="0" /></label><label>Opacity<input id="svg-opacity" type="number" min="0" max="1" step="0.1" value="1" /></label></div><div class="svg-editor-actions"><button class="button" data-action="apply-edit">Apply edit</button><button class="button" data-action="fix-svg">Fix SVG</button><label>Optimizer<select id="svg-optimize-preset"><option value="safe">Safe</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select></label><button class="button" data-action="optimize">Optimize</button></div></section><section class="svg-copy-panel"><h3>Copy formats</h3><div class="svg-copy-actions"><button class="button" data-copy-format="html">HTML</button><button class="button" data-copy-format="data">Data URI</button><button class="button" data-copy-format="background">CSS background</button><button class="button" data-copy-format="mask">CSS mask</button><button class="button" data-copy-format="jsx">JSX</button></div></section></main>
      <aside class="svg-inspector" aria-label="SVG inspector"><div class="svg-inspector-heading"><div><span class="eyebrow">INSPECTOR</span><h3>${current.title}</h3></div><span class="svg-status-badge" data-status="${inspector.status}">${inspector.status}</span></div><div class="svg-score"><strong>${inspector.score}/100</strong><span>SVG Technical Score</span></div><dl class="svg-metrics"><div><dt>viewBox</dt><dd>${inspector.viewBox || '—'}</dd></div><div><dt>Paths</dt><dd>${inspector.pathCount}</dd></div><div><dt>Groups</dt><dd>${inspector.groupCount}</dd></div><div><dt>File size</dt><dd>${inspector.byteSize.toLocaleString()} bytes</dd></div><div><dt>Fill / stroke</dt><dd>${inspector.fills.join(', ') || '—'} / ${inspector.strokes.join(', ') || '—'}</dd></div></dl><div class="svg-check-list">${inspector.checks.map((check) => `<div class="svg-check" data-status="${check.status}"><strong>${check.status}</strong><span>${check.label}</span><small>${check.detail}</small></div>`).join('')}</div><div class="svg-upload"><h3>Upload your own SVG</h3><label class="file-drop"><strong>Choose SVG</strong><input id="svg-upload" type="file" accept="image/svg+xml,.svg" /></label><small>Sanitized locally before preview. Maximum 2 MB.</small></div><div class="svg-pack-panel"><h3>Selected pack (${selectedPack.size})</h3><button class="button button--primary" data-action="build-pack" ${selectedPack.size ? '' : 'disabled'}>Build icon pack ZIP</button><small>Includes SVG, sprite.svg, icons.css, manifest.json and LICENSES.txt.</small></div></aside></div></section>`;
    displaySvg();
    bind();
  };

  const bind = () => {
    container.querySelector<HTMLInputElement>('#svg-search')?.addEventListener('input', render);
    container.querySelector<HTMLSelectElement>('#svg-category')?.addEventListener('change', render);
    container.querySelector<HTMLSelectElement>('#svg-style')?.addEventListener('change', render);
    container.querySelector<HTMLSelectElement>('#svg-license')?.addEventListener('change', render);
    container.querySelector<HTMLSelectElement>('#svg-preview-bg')?.addEventListener('change', (event) => { currentBg = (event.target as HTMLSelectElement).value; render(); });
    container.querySelector<HTMLSelectElement>('#svg-preview-size')?.addEventListener('change', (event) => { currentSize = Number((event.target as HTMLSelectElement).value); displaySvg(); });
    container.querySelector<HTMLSelectElement>('#svg-color-mode')?.addEventListener('change', (event) => { colorMode = (event.target as HTMLSelectElement).value as ColorMode; });
    container.querySelector<HTMLSelectElement>('#svg-optimize-preset')?.addEventListener('change', (event) => { optimizePreset = (event.target as HTMLSelectElement).value as OptimizePreset; });
    container.querySelectorAll<HTMLElement>('[data-action]').forEach((button) => button.addEventListener('click', () => void handleAction(button.dataset.action || '', button.dataset.svgId)));
    container.querySelectorAll<HTMLElement>('[data-copy-format]').forEach((button) => button.addEventListener('click', () => { const format = button.dataset.copyFormat; const value = format === 'html' ? htmlSnippet(currentSvg) : format === 'data' ? svgToDataUri(currentSvg) : format === 'background' ? cssBackgroundSnippet(currentSvg) : format === 'mask' ? cssMaskSnippet(currentSvg, `.icon-${current.id}`) : jsxSnippet(currentSvg); void copyText(value, `${format} format`); }));
    container.querySelector<HTMLInputElement>('#svg-upload')?.addEventListener('change', (event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (file) void loadUploaded(file); });
  };

  const handleAction = async (action: string, assetId?: string) => {
    if (assetId) {
      const asset = assetById(assetId); if (!asset) return;
      if (action === 'open') { await loadAsset(asset); return; }
      if (action === 'favorite') { favorites.has(asset.id) ? favorites.delete(asset.id) : favorites.add(asset.id); saveIds(FAVORITES_KEY, [...favorites]); render(); return; }
      if (action === 'pack') { selectedPack.has(asset.id) ? selectedPack.delete(asset.id) : selectedPack.add(asset.id); render(); return; }
      if (action === 'copy') { const response = await fetch(asset.assetUrl); void copyText(await response.text(), `${asset.title} SVG`); return; }
    }
    if (action === 'copy-raw') { void copyText(currentSvg, 'SVG'); return; }
    if (action === 'download-svg') { download(new Blob([currentSvg], { type: 'image/svg+xml' }), `${current.id}.svg`); setStatus('SVG download ready', 'success'); return; }
    if (action === 'download-png') { try { download(await renderSvgToPng(currentSvg, currentSize, 1), `${current.id}-${currentSize}px.png`); setStatus('PNG export ready', 'success'); } catch (error) { setStatus(error instanceof Error ? error.message : 'PNG export failed', 'error'); } return; }
    if (action === 'apply-edit') { const controls = readEditorControls(); currentSvg = applySvgEdits(currentSvg, controls); inspector = inspectSvgMarkup(currentSvg); displaySvg(); updateInspector(); setStatus('Edit applied to local SVG', 'success'); return; }
    if (action === 'fix-svg') { const result = sanitizeSvgMarkup(currentSvg); currentSvg = optimizeSvgMarkup(result.svg, 'safe').svg; inspector = inspectSvgMarkup(currentSvg); displaySvg(); updateInspector(); setStatus(`Fix SVG removed ${result.removed.length} unsafe/redundant item(s)`, 'success'); return; }
    if (action === 'optimize') { const result = optimizeSvgMarkup(currentSvg, optimizePreset); currentSvg = result.svg; inspector = inspectSvgMarkup(currentSvg); displaySvg(); updateInspector(); setStatus(`Optimized ${result.beforeBytes} → ${result.afterBytes} bytes`, 'success'); return; }
    if (action === 'build-pack') { await buildPack(); return; }
  };

  const readEditorControls = () => ({ colorMode, color: container.querySelector<HTMLInputElement>('#svg-color')?.value || '#2563eb', stroke: container.querySelector<HTMLInputElement>('#svg-color')?.value || 'currentColor', strokeWidth: Number(container.querySelector<HTMLInputElement>('#svg-stroke-width')?.value || 1.5), width: '', height: '', rotation: Number(container.querySelector<HTMLInputElement>('#svg-rotation')?.value || 0), flipX: false, flipY: false, padding: Number(container.querySelector<HTMLInputElement>('#svg-padding')?.value || 0), background: '', opacity: Number(container.querySelector<HTMLInputElement>('#svg-opacity')?.value || 1) });
  const updateInspector = () => { const badge = container.querySelector<HTMLElement>('.svg-status-badge'); if (badge) { badge.textContent = inspector.status; badge.dataset.status = inspector.status; } const score = container.querySelector<HTMLElement>('.svg-score strong'); if (score) score.textContent = `${inspector.score}/100`; const metrics = container.querySelector<HTMLElement>('.svg-metrics'); if (metrics) metrics.innerHTML = `<div><dt>viewBox</dt><dd>${inspector.viewBox || '—'}</dd></div><div><dt>Paths</dt><dd>${inspector.pathCount}</dd></div><div><dt>Groups</dt><dd>${inspector.groupCount}</dd></div><div><dt>File size</dt><dd>${inspector.byteSize.toLocaleString()} bytes</dd></div><div><dt>Fill / stroke</dt><dd>${inspector.fills.join(', ') || '—'} / ${inspector.strokes.join(', ') || '—'}</dd></div>`; const list = container.querySelector<HTMLElement>('.svg-check-list'); if (list) list.innerHTML = inspector.checks.map((check) => `<div class="svg-check" data-status="${check.status}"><strong>${check.status}</strong><span>${check.label}</span><small>${check.detail}</small></div>`).join(''); };
  const loadUploaded = async (file: File) => { if (file.size > 2 * 1024 * 1024) { setStatus('SVG exceeds the 2 MB safety limit', 'error'); return; } try { const result = sanitizeSvgMarkup(await file.text()); currentSvg = result.svg; current = { id: 'uploaded-svg', title: file.name.replace(/\.svg$/i, '') || 'Uploaded SVG', keywords: ['uploaded', 'custom', 'svg'], category: 'uploaded', style: 'outline', properties: ['local'], source: 'User-provided SVG', author: 'User', license: 'User-provided', licenseUrl: '/docs/svg-library-license-policy.md', sourceUrl: 'local-upload', attributionRequired: false, commercialUseAllowed: false, modifiedAllowed: true, assetUrl: '', filename: file.name, viewBox: inspectSvgMarkup(currentSvg).viewBox || '0 0 24 24' }; customUploaded = true; inspector = inspectSvgMarkup(currentSvg); render(); setStatus(`Uploaded and sanitized locally; ${result.removed.length} item(s) removed`, 'success'); } catch (error) { setStatus(error instanceof Error ? error.message : 'SVG upload failed', 'error'); } };
  const buildPack = async () => { const assets = currentPackAssets(); if (!assets.length) return; try { const files = []; for (const asset of assets) { const svg = asset.id === current.id && !customUploaded ? currentSvg : sanitizeSvgMarkup(await (await fetch(asset.assetUrl)).text()).svg; files.push({ name: `svg/${asset.filename}`, bytes: bytes(svg) }); } files.push({ name: 'sprite.svg', bytes: bytes(buildSprite(await Promise.all(assets.map(async (asset) => ({ id: asset.id, svg: asset.id === current.id && !customUploaded ? currentSvg : sanitizeSvgMarkup(await (await fetch(asset.assetUrl)).text()).svg, viewBox: asset.viewBox }))))) }); files.push({ name: 'icons.css', bytes: bytes(buildCssPack(assets)) }, { name: 'manifest.json', bytes: bytes(buildManifestJson(assets)) }, { name: 'LICENSES.txt', bytes: bytes(buildLicensesTxt(assets)) }); download(createZip(files), 'my-icon-pack.zip'); setStatus(`Icon pack ready with ${assets.length} assets`, 'success'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Pack build failed', 'error'); } };

  void loadAsset(current);
  return;
};

export const unmount = (): void => { /* UI state is local and object URLs are revoked after each PNG export. */ };
export { metadata };
