import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { downloadUrl, setToolStatus } from '../../core/tool-ui';
import type { ToolModule } from '../../core/tool-contract';
import { buildCSV, buildGeoJSON, buildKML } from './exporters';
import { getSegments, polygonAreaSquareMeters, polygonCentroid, totalDistance, validatePoint, type GeoPoint } from './geometry';
import { formatArea, formatMeters } from './units';
import { metadata } from './metadata';
import './land-measurement.css';

let activeUnmount: (() => void) | undefined;
const center: [number, number] = [13.7563, 100.5018];

function uid(): string { return `point-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }

class LandMeasurementController {
  private readonly container: HTMLElement; private map?: L.Map; private basemap?: L.TileLayer; private satellite?: L.TileLayer; private markers = new Map<string, L.Marker>(); private line?: L.Polyline; private polygon?: L.Polygon; private points: GeoPoint[] = []; private mode: 'distance' | 'area' | 'gps' = 'distance'; private layer: 'standard' | 'satellite' = 'standard'; private onKeyDown?: (event: KeyboardEvent) => void;
  constructor(container: HTMLElement) { this.container = container; }
  mount(): void { this.container.innerHTML = `<section class="utility-panel land-measurement" aria-labelledby="land-title"><header class="land-header"><div><p class="eyebrow">Local map measurement / วัดจาก browser</p><h2 id="land-title">วัดระยะและพื้นที่แปลง</h2><p class="helper-text">แตะจุดบนแผนที่เพื่อวัดระยะ เส้นรอบรูป หรือพื้นที่แปลง</p></div><span class="privacy-badge">Local geometry / ไม่อัปโหลดพิกัด</span></header><div class="land-disclaimer" role="note">ผลการวัดเป็นค่าประมาณจากพิกัดและแผนที่ ไม่ใช้แทนการรังวัดโดยเจ้าหน้าที่หรือเครื่องมือสำรวจมาตรฐาน</div><div class="land-toolbar" role="toolbar" aria-label="Measurement controls"><div class="land-mode-buttons"><button type="button" class="button is-active" data-mode="distance">วัดระยะ</button><button type="button" class="button" data-mode="area">วัดพื้นที่</button><button type="button" class="button" data-mode="gps">เดินวัด GPS</button></div><div class="land-map-buttons"><button type="button" class="button button--secondary" data-action="locate">ตำแหน่งของฉัน</button><button type="button" class="button button--secondary" data-action="layer">แผนที่ / ดาวเทียม</button></div></div><div class="land-layout"><div class="land-map-wrap"><div id="land-map" class="land-map" aria-label="Interactive measurement map"></div><p id="land-status" class="tool-status" aria-live="polite">เลือกโหมด แล้วแตะบนแผนที่เพื่อเพิ่มจุด</p></div><aside class="land-results" aria-labelledby="land-results-title"><h3 id="land-results-title">ผลการวัด / Results</h3><div id="land-summary" class="land-summary"></div><div id="land-points" class="land-points"></div><div class="land-actions"><button type="button" class="button button--secondary" data-action="undo">ย้อนจุดล่าสุด</button><button type="button" class="button button--secondary" data-action="clear">ล้างทั้งหมด</button></div><div class="land-exports"><strong>ส่งออก / Export</strong><div><button type="button" class="button" data-export="geojson">GeoJSON</button><button type="button" class="button" data-export="kml">KML</button><button type="button" class="button" data-export="csv">CSV</button><button type="button" class="button button--primary" data-action="copy">คัดลอกผลลัพธ์</button></div></div><p class="helper-text">แผนที่มาตรฐานโหลดจาก OpenStreetMap เมื่อออนไลน์; โหมดดาวเทียมใช้ Esri tiles และอาจมีเงื่อนไขผู้ให้บริการ</p></aside></div></section>`; this.initMap(); this.bind(); this.render(); }
  private initMap(): void { const host = this.container.querySelector<HTMLElement>('#land-map'); if (!host) return; this.map = L.map(host, { zoomControl: true }).setView(center, 13); this.basemap = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; OpenStreetMap contributors', maxZoom: 19 }).addTo(this.map); this.map.on('click', (event) => this.addPoint(event.latlng.lat, event.latlng.lng, 'map')); setTimeout(() => this.map?.invalidateSize(), 0); }
  private bind(): void { this.container.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach((button) => button.addEventListener('click', () => { this.mode = button.dataset.mode as typeof this.mode; this.container.querySelectorAll('[data-mode]').forEach((node) => node.classList.toggle('is-active', node === button)); this.setStatus(this.mode === 'gps' ? 'กด “บันทึกจุด GPS” แล้วเดินไปมุมถัดไป / Press GPS capture at each corner' : 'แตะบนแผนที่เพื่อเพิ่มจุด / Tap the map to add a point'); this.render(); })); this.container.querySelector<HTMLButtonElement>('[data-action="layer"]')?.addEventListener('click', () => this.toggleLayer()); this.container.querySelector<HTMLButtonElement>('[data-action="locate"]')?.addEventListener('click', () => this.locate()); this.container.querySelector<HTMLButtonElement>('[data-action="undo"]')?.addEventListener('click', () => { this.points.pop(); this.render(); }); this.container.querySelector<HTMLButtonElement>('[data-action="clear"]')?.addEventListener('click', () => { this.points = []; this.render(); this.setStatus('ล้างข้อมูลการวัดแล้ว / Measurement cleared', 'success'); }); this.container.querySelector<HTMLButtonElement>('[data-action="copy"]')?.addEventListener('click', () => void this.copySummary()); this.container.querySelector<HTMLButtonElement>('[data-action="capture"]')?.addEventListener('click', () => this.captureGps()); this.container.querySelectorAll<HTMLButtonElement>('[data-export]').forEach((button) => button.addEventListener('click', () => this.export(button.dataset.export as 'geojson' | 'kml' | 'csv'))); this.onKeyDown = (event) => { if (event.key === 'Escape') { this.points = []; this.render(); this.setStatus('ล้างข้อมูลการวัดแล้ว / Measurement cleared', 'success'); } }; document.addEventListener('keydown', this.onKeyDown); }
  private addPoint(lat: number, lng: number, source: 'map' | 'gps', accuracyMeters?: number): void { if (!validatePoint(lat, lng)) return; const point: GeoPoint = { id: uid(), lat, lng, source, accuracyMeters, createdAt: Date.now() }; this.points.push(point); this.render(); }
  private render(): void { this.markers.forEach((marker) => marker.remove()); this.markers.clear(); this.line?.remove(); this.polygon?.remove(); if (!this.map) return; this.points.forEach((point, index) => { const marker = L.marker([point.lat, point.lng], { draggable: true }).addTo(this.map!).bindTooltip(String(index + 1), { permanent: true, direction: 'top' }); marker.on('dragend', () => { const position = marker.getLatLng(); const target = this.points.find((item) => item.id === point.id); if (target) { target.lat = position.lat; target.lng = position.lng; this.render(); } }); this.markers.set(point.id, marker); }); const latLngs = this.points.map((point) => [point.lat, point.lng] as [number, number]); if (latLngs.length >= 2) this.line = L.polyline(latLngs, { color: '#2563eb', weight: 4 }).addTo(this.map); if (this.mode === 'area' && latLngs.length >= 3) this.polygon = L.polygon(latLngs, { color: '#0f766e', fillColor: '#14b8a6', fillOpacity: 0.22 }).addTo(this.map); const gpsButton = this.container.querySelector<HTMLButtonElement>('[data-action="capture"]'); if (gpsButton) gpsButton.remove(); if (this.mode === 'gps') { const button = document.createElement('button'); button.type = 'button'; button.className = 'button button--primary land-gps-capture'; button.dataset.action = 'capture'; button.textContent = 'บันทึกจุด GPS / Capture GPS point'; button.addEventListener('click', () => this.captureGps()); this.container.querySelector('.land-map-buttons')?.append(button); } this.renderResults(); }
  private renderResults(): void { const summary = this.container.querySelector<HTMLElement>('#land-summary'); const points = this.container.querySelector<HTMLElement>('#land-points'); if (!summary || !points) return; const closed = this.mode === 'area'; const segments = getSegments(this.points, closed); const perimeter = segments.reduce((sum, segment) => sum + segment.meters, 0); const area = this.mode === 'area' ? polygonAreaSquareMeters(this.points) : 0; const centroid = this.mode === 'area' ? polygonCentroid(this.points) : null; summary.innerHTML = `<div class="land-metric"><span>${this.mode === 'area' ? 'พื้นที่ / Area' : 'ระยะรวม / Total distance'}</span><strong>${this.mode === 'area' ? (this.points.length >= 3 ? formatArea(area) : 'เพิ่มอย่างน้อย 3 จุดเพื่อคำนวณพื้นที่') : formatMeters(perimeter)}</strong></div>${this.mode === 'area' && this.points.length >= 3 ? `<div class="land-metric"><span>เส้นรอบรูป / Perimeter</span><strong>${formatMeters(perimeter)}</strong></div><div class="land-metric"><span>ศูนย์กลางโดยประมาณ / Centroid</span><strong>${centroid ? `${centroid.lat.toFixed(6)}, ${centroid.lng.toFixed(6)}` : '-'}</strong></div>` : ''}<div class="land-segments"><strong>ระยะรายด้าน / Segments</strong>${segments.length ? `<ol>${segments.map((segment) => `<li>P${segment.from + 1} → P${segment.to + 1}: ${formatMeters(segment.meters)}</li>`).join('')}</ol>` : '<p>เพิ่มอย่างน้อย 2 จุด / Add at least two points</p>'}</div>`; points.innerHTML = this.points.length ? `<h4>จุดที่ปัก / Points (${this.points.length})</h4><ol>${this.points.map((point, index) => `<li><button type="button" class="land-point-delete" data-delete="${point.id}" aria-label="ลบจุดที่ ${index + 1}">×</button><span>${index + 1}. ${point.lat.toFixed(6)}, ${point.lng.toFixed(6)} <small>${point.source}${point.accuracyMeters ? ` ±${Math.round(point.accuracyMeters)} m` : ''}</small></span></li>`).join('')}</ol>` : '<p>ยังไม่มีจุด / No points yet</p>'; points.querySelectorAll<HTMLButtonElement>('[data-delete]').forEach((button) => button.addEventListener('click', () => { this.points = this.points.filter((point) => point.id !== button.dataset.delete); this.render(); })); }
  private toggleLayer(): void { if (!this.map) return; if (this.layer === 'standard') { this.basemap?.remove(); this.satellite = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', { attribution: 'Tiles &copy; Esri', maxZoom: 19 }).addTo(this.map); this.layer = 'satellite'; } else { this.satellite?.remove(); this.basemap?.addTo(this.map); this.layer = 'standard'; } this.setStatus(this.layer === 'satellite' ? 'เปิดภาพดาวเทียมแล้ว / Satellite layer on' : 'เปิดแผนที่มาตรฐานแล้ว / Standard map on', 'success'); }
  private locate(): void { if (!navigator.geolocation) { this.setStatus('เบราว์เซอร์ไม่รองรับ GPS / Geolocation is unavailable', 'error'); return; } this.setStatus('กำลังค้นหาตำแหน่ง / Locating…', 'working'); navigator.geolocation.getCurrentPosition((position) => { const { latitude, longitude, accuracy } = position.coords; this.map?.setView([latitude, longitude], 17); L.circle([latitude, longitude], { radius: accuracy, color: '#f59e0b', fillOpacity: 0.12 }).addTo(this.map!); this.setStatus(`ตำแหน่งโดยประมาณ ±${Math.round(accuracy)} m / Location accuracy ±${Math.round(accuracy)} m`, 'success'); }, (error) => this.setStatus(error.code === 1 ? 'ไม่ได้รับสิทธิ์ตำแหน่ง / Location permission denied' : 'ค้นหาตำแหน่งไม่สำเร็จ / Location unavailable', 'error'), { enableHighAccuracy: true, timeout: 12_000, maximumAge: 10_000 }); }
  private captureGps(): void { if (!navigator.geolocation) { this.setStatus('เบราว์เซอร์ไม่รองรับ GPS / Geolocation is unavailable', 'error'); return; } this.setStatus('กำลังอ่าน GPS / Reading GPS…', 'working'); navigator.geolocation.getCurrentPosition((position) => this.addPoint(position.coords.latitude, position.coords.longitude, 'gps', position.coords.accuracy), () => this.setStatus('อ่าน GPS ไม่สำเร็จ กรุณาตรวจ permission และสัญญาณ / GPS failed', 'error'), { enableHighAccuracy: true, timeout: 12_000, maximumAge: 0 }); }
  private summaryText(): string { const area = this.mode === 'area' ? polygonAreaSquareMeters(this.points) : 0; return `Land Measurement / วัดระยะและพื้นที่แปลง\nMode: ${this.mode}\nPoints: ${this.points.length}\nTotal: ${formatMeters(totalDistance(this.points, this.mode === 'area'))}${area ? `\nArea: ${formatArea(area)}` : ''}\n${this.points.map((point, index) => `${index + 1}. ${point.lat.toFixed(6)}, ${point.lng.toFixed(6)} (${point.source})`).join('\n')}`; }
  private async copySummary(): Promise<void> { const text = this.summaryText(); try { if (navigator.clipboard) await navigator.clipboard.writeText(text); else { const textarea = document.createElement('textarea'); textarea.value = text; textarea.style.position = 'fixed'; textarea.style.opacity = '0'; document.body.append(textarea); textarea.select(); if (!document.execCommand('copy')) throw new Error('Copy failed'); textarea.remove(); } this.setStatus('คัดลอกผลการวัดแล้ว / Summary copied', 'success'); } catch { this.setStatus('คัดลอกไม่สำเร็จ / Copy failed', 'error'); } }
  private export(format: 'geojson' | 'kml' | 'csv'): void { if (!this.points.length) { this.setStatus('เพิ่มจุดก่อนส่งออก / Add points before export', 'error'); return; } const content = format === 'geojson' ? buildGeoJSON(this.points, this.mode) : format === 'kml' ? buildKML(this.points, this.mode) : buildCSV(this.points); const mime = format === 'geojson' ? 'application/geo+json' : format === 'kml' ? 'application/vnd.google-earth.kml+xml' : 'text/csv;charset=utf-8'; const url = URL.createObjectURL(new Blob([content], { type: mime })); downloadUrl(url, `land-measurement-${format}.${format === 'geojson' ? 'geojson' : format}`); window.setTimeout(() => URL.revokeObjectURL(url), 1000); this.setStatus(`${format.toUpperCase()} สร้างแล้ว / Export created`, 'success'); }
  private setStatus(message: string, tone: 'neutral' | 'working' | 'success' | 'error' = 'neutral'): void { const output = this.container.querySelector<HTMLOutputElement>('#land-status'); if (output) setToolStatus(output, message, tone); }
  unmount(): void { if (this.onKeyDown) document.removeEventListener('keydown', this.onKeyDown); this.map?.remove(); this.map = undefined; this.points = []; this.markers.clear(); this.container.innerHTML = ''; }
}

export const mount = async (container: HTMLElement): Promise<void> => { const controller = new LandMeasurementController(container); activeUnmount = () => controller.unmount(); controller.mount(); };
export const unmount = (): void => { activeUnmount?.(); activeUnmount = undefined; };
export { metadata };
export default { metadata, mount, unmount } satisfies ToolModule;
