import { processAudioAsync } from '../core/processing-client';
import type { AudioOperation, AudioPcmData } from '../core/audio-processing';
import type { ToolMetadata, ToolModule } from '../core/tool-contract';
import { downloadUrl, formatBytes, getErrorMessage, isAbortError, setProgressStatus, setToolStatus } from '../core/tool-ui';

export type AudioWorkbenchKind = AudioOperation['kind'];

interface AudioWorkbenchConfig {
  kind: AudioWorkbenchKind;
  eyebrow: string;
  heading: string;
  intro: string;
  multiple?: boolean;
  outputSuffix: string;
}

interface LoadedAudio { file: File; pcm: AudioPcmData; duration: number; }

function formatTime(seconds: number): string { const safe = Math.max(0, seconds || 0); return `${String(Math.floor(safe / 60)).padStart(2, '0')}:${(safe % 60).toFixed(2).padStart(5, '0')}`; }
function pcmFromBuffer(buffer: AudioBuffer): AudioPcmData { return { sampleRate: buffer.sampleRate, channels: Array.from({ length: buffer.numberOfChannels }, (_, index) => new Float32Array(buffer.getChannelData(index))) }; }
function replaceExtension(filename: string, suffix: string): string { return `${filename.replace(/\.[^.]+$/, '')}${suffix}.wav`; }

function controls(config: AudioWorkbenchConfig): string {
  if (config.kind === 'compress') return `<div class="form-row"><label class="field" for="audio-target"><span>เป้าหมายขนาด / Target size (MB)</span><input id="audio-target" type="number" min="0.05" max="80" step="0.05" value="2" /></label><label class="field" for="audio-preset"><span>Preset</span><select id="audio-preset"><option value="speech">เสียงพูด / Speech</option><option value="podcast">พอดแคสต์ / Podcast</option><option value="music">เพลง / Music</option></select></label></div><p class="helper-text">ระบบจะเลือก sample rate ให้ใกล้เป้าหมายและรายงานขนาดก่อน/หลัง ไม่หลอกว่าเป็นการบีบอัดแบบ lossless</p>`;
  if (config.kind === 'merge') return `<div class="form-row"><label class="field" for="audio-gap"><span>ช่องว่าง / Gap (วินาที)</span><input id="audio-gap" type="number" min="0" max="10" step="0.1" value="0" /></label><label class="field" for="audio-crossfade"><span>Crossfade (วินาที)</span><input id="audio-crossfade" type="number" min="0" max="10" step="0.1" value="0" /></label></div><label class="field" for="audio-format"><span>Output format</span><select id="audio-format"><option value="wav">WAV PCM 16-bit</option><option value="wav-compact">WAV Compact 8-bit</option></select></label><p class="helper-text">เลือกไฟล์หลายรายการแล้วใช้ปุ่มเลื่อนขึ้น/ลงเพื่อจัดลำดับก่อนรวม</p>`;
  if (config.kind === 'silence') return `<div class="form-row"><label class="field" for="audio-threshold"><span>Threshold (dB)</span><input id="audio-threshold" type="number" min="-80" max="-1" step="1" value="-42" /></label><label class="field" for="audio-minimum"><span>Minimum silence (วินาที)</span><input id="audio-minimum" type="number" min="0.05" max="10" step="0.05" value="0.4" /></label></div><label class="field" for="audio-padding"><span>Padding รอบเสียงพูด (วินาที)</span><input id="audio-padding" type="number" min="0" max="2" step="0.01" value="0.08" /></label><p class="helper-text">ปรับ threshold และตรวจ Preview ก่อน export เพื่อไม่ตัดหางคำพูด</p>`;
  if (config.kind === 'finish') return `<div class="form-row"><label class="field" for="audio-gain"><span>Gain (dB)</span><input id="audio-gain" type="number" min="-12" max="12" step="0.5" value="0" /></label><label class="field field--check" for="audio-normalize"><span>Normalize peak</span><input id="audio-normalize" type="checkbox" checked /></label></div><div class="form-row"><label class="field" for="audio-fade-in"><span>Fade in (วินาที)</span><input id="audio-fade-in" type="number" min="0" max="30" step="0.1" value="0" /></label><label class="field" for="audio-fade-out"><span>Fade out (วินาที)</span><input id="audio-fade-out" type="number" min="0" max="30" step="0.1" value="0" /></label></div><p class="helper-text">Peak meter จะแจ้ง clipping risk ก่อนดาวน์โหลด และ limiter แบบนุ่มช่วยป้องกันการแตกจาก gain</p>`;
  return `<div class="form-row"><label class="field" for="audio-speed"><span>Speed / ความเร็ว</span><input id="audio-speed" type="number" min="0.25" max="4" step="0.05" value="1" /></label><label class="field" for="audio-semitones"><span>Pitch / โทนเสียง (semitones)</span><input id="audio-semitones" type="number" min="-12" max="12" step="1" value="0" /></label></div><p class="helper-text">Speed และ Pitch เป็นการ resample แบบ offline ที่คาดเดาผลลัพธ์ได้ ไม่อ้างว่าเป็น time-stretch คุณภาพสตูดิโอ</p>`;
}

function operationFromForm(kind: AudioWorkbenchKind, form: HTMLFormElement, segments: AudioPcmData[]): AudioOperation {
  if (kind === 'compress') return { kind, targetBytes: Number((form.querySelector('#audio-target') as HTMLInputElement).value) * 1024 * 1024, preset: (form.querySelector('#audio-preset') as HTMLSelectElement).value as 'speech' | 'music' | 'podcast' };
  if (kind === 'merge') return { kind, segments, gap: Number((form.querySelector('#audio-gap') as HTMLInputElement).value), crossfade: Number((form.querySelector('#audio-crossfade') as HTMLInputElement).value), format: (form.querySelector('#audio-format') as HTMLSelectElement).value as 'wav' | 'wav-compact' };
  if (kind === 'silence') return { kind, thresholdDb: Number((form.querySelector('#audio-threshold') as HTMLInputElement).value), minimum: Number((form.querySelector('#audio-minimum') as HTMLInputElement).value), padding: Number((form.querySelector('#audio-padding') as HTMLInputElement).value) };
  if (kind === 'finish') return { kind, normalize: (form.querySelector('#audio-normalize') as HTMLInputElement).checked, gainDb: Number((form.querySelector('#audio-gain') as HTMLInputElement).value), fadeIn: Number((form.querySelector('#audio-fade-in') as HTMLInputElement).value), fadeOut: Number((form.querySelector('#audio-fade-out') as HTMLInputElement).value) };
  return { kind, speed: Number((form.querySelector('#audio-speed') as HTMLInputElement).value), semitones: Number((form.querySelector('#audio-semitones') as HTMLInputElement).value) };
}

export function createAudioWorkbench(metadata: ToolMetadata, config: AudioWorkbenchConfig): ToolModule {
  let panel: HTMLElement | undefined; let loaded: LoadedAudio[] = []; let outputUrl = ''; let context: AudioContext | undefined; let controller: AbortController | undefined;
  const clearOutput = (): void => { if (outputUrl) URL.revokeObjectURL(outputUrl); outputUrl = ''; panel?.querySelector<HTMLElement>('#audio-result')?.setAttribute('hidden', ''); };
  const decode = async (file: File): Promise<LoadedAudio> => { context ??= new AudioContext(); const buffer = await context.decodeAudioData((await file.arrayBuffer()).slice(0)); return { file, pcm: pcmFromBuffer(buffer), duration: buffer.duration }; };
  const renderFiles = (): void => { const list = panel?.querySelector<HTMLElement>('#audio-file-list'); if (!list) return; list.innerHTML = loaded.map((item, index) => `<li><span><strong>${item.file.name}</strong><small>${formatTime(item.duration)} · ${formatBytes(item.file.size)}</small></span>${config.multiple ? `<button type="button" class="text-button" data-audio-move="up" data-index="${index}" ${index === 0 ? 'disabled' : ''}>ขึ้น / Up</button><button type="button" class="text-button" data-audio-move="down" data-index="${index}" ${index === loaded.length - 1 ? 'disabled' : ''}>ลง / Down</button>` : ''}</li>`).join(''); };
  const handleChange = async (event: Event): Promise<void> => { if (!panel) return; const input = event.currentTarget as HTMLInputElement; const status = panel.querySelector<HTMLOutputElement>('#audio-status'); controller?.abort(); controller = new AbortController(); clearOutput(); loaded = []; try { const files = [...(input.files ?? [])]; if (!files.length) throw new Error('กรุณาเลือกไฟล์เสียง'); if (files.some((file) => file.size > 80 * 1024 * 1024)) throw new Error('ไฟล์เสียงต้องมีขนาดไม่เกิน 80 MB ต่อไฟล์'); loaded = await Promise.all(files.map(decode)); renderFiles(); const first = loaded[0]!; const preview = panel.querySelector<HTMLAudioElement>('#audio-source-preview'); if (preview) preview.src = URL.createObjectURL(first.file); panel.querySelector<HTMLElement>('#audio-editor')?.removeAttribute('hidden'); if (status) setToolStatus(status, `อ่าน ${loaded.length} ไฟล์สำเร็จ · ${formatTime(loaded.reduce((sum, item) => sum + item.duration, 0))}`, 'success'); } catch (error) { if (status) setToolStatus(status, isAbortError(error) ? 'ยกเลิกการอ่านไฟล์เสียงแล้ว' : getErrorMessage(error), isAbortError(error) ? 'neutral' : 'error'); } };
  const handleSubmit = async (event: SubmitEvent): Promise<void> => { event.preventDefault(); if (!panel || !loaded.length) return; const status = panel.querySelector<HTMLOutputElement>('#audio-status'); controller?.abort(); controller = new AbortController(); const form = event.currentTarget as HTMLFormElement; try { const operation = operationFromForm(config.kind, form, loaded.map((item) => item.pcm)); const firstPcm = loaded[0]!.pcm; const result = await processAudioAsync(firstPcm, operation, { signal: controller.signal, onProgress: (progress, message) => { if (status) setProgressStatus(status, progress, message); } }); if (controller.signal.aborted) throw new DOMException('ยกเลิกการประมวลผลแล้ว', 'AbortError'); outputUrl = URL.createObjectURL(new Blob([result.bytes.buffer as ArrayBuffer], { type: 'audio/wav' })); const resultBox = panel.querySelector<HTMLElement>('#audio-result'); resultBox?.removeAttribute('hidden'); const outputPreview = panel.querySelector<HTMLAudioElement>('#audio-output-preview'); if (outputPreview) outputPreview.src = outputUrl; const metrics = panel.querySelector<HTMLElement>('#audio-result-meta'); if (metrics) metrics.textContent = `${formatTime(result.duration)} · ${result.channels} ch · ${result.sampleRate.toLocaleString()} Hz · Peak ${(result.peak * 100).toFixed(1)}% · ${formatBytes(result.bytes.byteLength)}${result.clipped ? ' · Warning: clipping risk' : ''}`; if (status) setToolStatus(status, 'ประมวลผลสำเร็จ / Processing complete', 'success'); } catch (error) { if (status) setToolStatus(status, isAbortError(error) ? 'ยกเลิกการประมวลผลแล้ว' : getErrorMessage(error), isAbortError(error) ? 'neutral' : 'error'); } };
  const handleClick = (event: Event): void => { const target = event.target as HTMLElement; const move = target.closest<HTMLButtonElement>('[data-audio-move]'); if (move) { const index = Number(move.dataset.index); const direction = move.dataset.audioMove === 'up' ? -1 : 1; const next = index + direction; if (next >= 0 && next < loaded.length) [loaded[index], loaded[next]] = [loaded[next]!, loaded[index]!]; renderFiles(); return; } const action = target.closest<HTMLElement>('[data-audio-action]')?.dataset.audioAction; if (action === 'preview') panel?.querySelector<HTMLAudioElement>('#audio-source-preview')?.play(); if (action === 'cancel') controller?.abort(); if (action === 'download' && outputUrl && loaded[0]) downloadUrl(outputUrl, replaceExtension(loaded[0].file.name, config.outputSuffix)); };
  return { metadata, mount(container) { panel = document.createElement('section'); panel.className = 'utility-panel'; panel.innerHTML = `<div class="utility-panel__header"><div><p class="eyebrow">${config.eyebrow}</p><h2>${config.heading}</h2><p class="helper-text">${config.intro}</p></div></div><form class="tool-form" id="audio-form"><label class="file-drop" for="audio-file"><strong>${config.multiple ? 'เลือกไฟล์เสียงหลายรายการ / Select audio files' : 'เลือกไฟล์เสียง / Select audio file'}</strong><span>MP3, WAV, M4A, OGG, WebM · สูงสุด 80 MB ต่อไฟล์</span><input id="audio-file" type="file" accept="audio/*,.mp3,.wav,.m4a,.ogg,.webm" ${config.multiple ? 'multiple' : ''} required /></label><section id="audio-editor" class="audio-editor" hidden><ol id="audio-file-list" class="audio-file-list"></ol><div class="audio-preview-row"><audio id="audio-source-preview" controls preload="metadata"></audio><button class="button" type="button" data-audio-action="preview">Preview ก่อนประมวลผล</button></div>${controls(config)}</section><div class="tool-actions"><button class="button button--primary" type="submit">ประมวลผล / Process</button><button class="button" type="button" data-audio-action="cancel">ยกเลิก / Cancel</button></div></form><section id="audio-result" class="download-result" hidden><div><strong>ผลลัพธ์ / Result</strong><p id="audio-result-meta"></p><audio id="audio-output-preview" controls preload="metadata"></audio></div><button class="button" type="button" data-audio-action="download">ดาวน์โหลด WAV / Download</button></section><output id="audio-status" class="tool-status" aria-live="polite">ไฟล์ประมวลผลบนอุปกรณ์ของคุณ / Files stay on your device.</output>`; panel.querySelector<HTMLInputElement>('#audio-file')!.addEventListener('change', (event) => void handleChange(event)); panel.querySelector<HTMLFormElement>('#audio-form')!.addEventListener('submit', (event) => void handleSubmit(event)); panel.addEventListener('click', handleClick); container.append(panel); }, unmount() { controller?.abort(); clearOutput(); panel?.remove(); context?.close(); context = undefined; loaded = []; panel = undefined; } };
}
